FROM node:alpine

WORKDIR /app

COPY package.json ./
COPY ./.env .
COPY ./tsconfig.json .
COPY src src
COPY dist dist

RUN npm install
RUN npm install pm2 -g
RUN ls -la

EXPOSE 3500

CMD ["pm2-runtime", "dist/index.js"]